language: node_js
node_js:
- '8'

# add known host, needed for server deploy
# ssh_known_hosts addon currently does not work with env var
# see https://github.com/travis-ci/travis-ci/issues/7043
# addons:
#   ssh_known_hosts: $deploy_host
before_script:
  - echo -e "Host $deploy_host\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script: npm run build

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist
    on:
      branch: master
  - provider: script
    script: bash server/deploy.sh
    on:
      branch: master
